// Single source of truth for the rich Markdown report — used by the website
// report export (ReportStep). Mirrors the self-hosted dashboard download so
// every surface produces the same document: dimension scores table, per-
// dimension Method + Coverage + findings (with fixes), Test Coverage, Security
// Findings summary, and the Tier-2 run when present.
import { buildDimensionGroups, overallFromGroups } from './buildDimensionGroups';
import { dimensionMeta } from '../data/dimensionMeta';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Results = Record<string, any>;

export function buildMarkdownReport(results: Results, tier2?: Results | null): string {
  const r = results || {};
  const codebase = r.codebase || {};
  const unit = r.unit || {};
  const security = r.security || {};
  const groups = buildDimensionGroups(r);
  const overall = overallFromGroups(groups);
  const L: string[] = [];

  L.push(`# TestForge Report — ${r.repo || 'project'}`, '');
  L.push(`**Overall:** ${overall}/100  ·  ${codebase.totalFiles || 0} files · ${(codebase.totalLines || 0).toLocaleString()} lines · ${codebase.endpoints || 0} endpoints`);
  L.push(`**Stack:** ${(codebase.techStack || []).join(', ') || 'n/a'}`);
  L.push(`**Branch:** ${r.branch || 'main'}  ·  **Analyzed:** ${r.analyzedAt || new Date().toISOString()}`, '');

  L.push('## Dimension scores', '', '| Dimension | Score | Findings |', '|---|---|---|');
  groups.forEach((g) => L.push(`| ${g.label} | ${g.score == null ? 'N/A' : g.score + '/100'} | ${g.findingCount} |`));
  L.push('');

  L.push('## Findings by dimension');
  groups.forEach((g) => {
    const m = dimensionMeta[g.key];
    L.push('', `### ${g.label} — ${g.score == null ? 'N/A' : g.score + '/100'}`);
    if (m) {
      if (m.methodology) L.push(`*Method:* ${m.methodology}`);
      if (m.languageCoverage) L.push(`*Coverage:* ${m.languageCoverage}`);
      if (g.score == null && m.naCriteria) L.push(`*Why N/A:* ${g.naReason || m.naCriteria}`);
    }
    if (g.findings.length) {
      L.push('');
      g.findings.forEach((f) => {
        const loc = f.filePath ? ` — \`${f.filePath}${f.lineNumber ? ':' + f.lineNumber : ''}\`` : '';
        L.push(`- **[${(f.severity || 'low').toUpperCase()}]** ${f.title}${loc}`);
        if (f.description) L.push(`  - ${f.description}`);
        if (f.fixSuggestion) L.push(`  - _Fix:_ ${f.fixSuggestion}`);
      });
    } else if (g.score != null) {
      L.push('', '_No issues found in this dimension._');
    }
  });

  L.push('', '## Test coverage', '', '| Metric | Value |', '|---|---|');
  L.push(`| Estimated function coverage | ${unit.coverage != null ? unit.coverage + '%' : 'n/a'} |`);
  L.push(`| Test files | ${unit.testFiles != null ? unit.testFiles : 'n/a'} |`);
  L.push(`| Test cases | ${unit.totalTests != null ? unit.totalTests : 'n/a'} |`);
  L.push(`| Frameworks | ${(unit.frameworks || []).join(', ') || 'none'} |`, '');

  L.push('## Security findings', '');
  L.push(`${security.findings != null ? security.findings : (security.items || []).length} total · ${security.critical || 0} critical · ${security.high || 0} high · ${security.medium || 0} medium · ${security.low || 0} low`);
  (security.items || []).forEach((f: Results) => {
    const loc = f.filePath ? ` — \`${f.filePath}${f.lineNumber ? ':' + f.lineNumber : ''}\`` : '';
    L.push(`- **[${(f.severity || 'low').toUpperCase()}]** ${f.title}${loc}`);
    if (f.fixSuggestion) L.push(`  - _Fix:_ ${f.fixSuggestion}`);
  });
  L.push('');

  if (tier2 && tier2.results) {
    const run = tier2.run || {};
    L.push('## Tier 2 — Generated tests', '');
    let head = `Model: ${tier2.provider?.byok ? 'your key' : (tier2.provider?.primary || 'n/a')}`;
    head += run.dockerUnavailable ? ` · sandbox: not run (${run.dockerUnavailable.reason})` : (run.numTotalTests != null ? ` · ${run.numPassedTests}/${run.numTotalTests} tests passed` : '');
    L.push(head);
    (tier2.results || []).forEach((res: Results, i: number) => {
      const fr = (run.files || [])[i];
      const status = fr ? (fr.status === 'skipped' ? 'generated (not run)' : `${fr.status} ${fr.numPassed}/${fr.numPassed + fr.numFailed}`) : 'generated';
      L.push(`- \`${res.file ? res.file.filename : '(no file)'}\` — ${status}${res.finding?.title ? ' · for: ' + res.finding.title : ''}`);
    });
    L.push('');
  }

  L.push('---', '*Generated by TestForge · testforge.run*');
  return L.join('\n');
}
