import type { LucideIcon } from 'lucide-react';
import {
  ScanLine,
  Target,
  Grid3x3,
  Gauge,
  Brain,
  Shield,
  Eye,
  Accessibility,
  CloudLightning,
  Dna,
  CheckCircle,
  FileSignature,
  GitBranch,
} from 'lucide-react';

export interface Dimension {
  id: string;
  num: string;
  shortName: string;
  fullName: string;
  tagline: string;
  description: string;
  metrics: string[];
  features: string[];
  icon: LucideIcon;
  category: string;
  executionSpeed: string;
  coverageDepth: string;
  aiEnhancement: string;
}

export const dimensions: Dimension[] = [
  {
    id: 'scope',
    num: '01',
    shortName: 'Scope',
    fullName: 'Scope Testing',
    tagline: 'Requirements coverage & boundary validation',
    description:
      'Scope Testing ensures every requirement is covered by at least one test case. TestForge parses your PRDs, user stories, and acceptance criteria — then maps them against your codebase to identify gaps. Boundary validation checks edge conditions, null inputs, and limit values that human testers often miss.',
    metrics: ['98% coverage', 'Auto PRD parsing', 'Boundary detection'],
    features: [
      'Automatic requirements extraction from PRDs and issues',
      'Coverage gap identification with risk-weighted prioritization',
      'Boundary value analysis for every input parameter',
      'Requirement-to-test traceability matrix',
    ],
    icon: ScanLine,
    category: 'Functional',
    executionSpeed: 'Fast',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'vision',
    num: '02',
    shortName: 'Vision',
    fullName: 'Vision & Goal Testing',
    tagline: 'Business goal alignment & outcome prediction',
    description:
      "Does your code actually achieve the business goal? Vision & Goal Testing measures alignment between implemented features and intended outcomes. TestForge predicts user behavior patterns and validates that the code produces the desired business results — not just technically correct outputs.",
    metrics: ['94% alignment', 'Outcome prediction', 'Goal tracking'],
    features: [
      'Business goal extraction from product documentation',
      'Feature-to-outcome mapping and scoring',
      'User journey validation against intended paths',
      'ROI impact estimation for each feature',
    ],
    icon: Target,
    category: 'Functional',
    executionSpeed: 'Medium',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'matrix',
    num: '03',
    shortName: 'Matrix',
    fullName: 'Feature Matrix Testing',
    tagline: 'Traceability matrices & impact analysis',
    description:
      'Feature Matrix Testing automatically generates and maintains traceability matrices linking requirements, tests, code, and deployments. When a change occurs, impact analysis identifies every affected component — preventing regression surprises.',
    metrics: ['Auto-generated', 'Impact analysis', 'Full traceability'],
    features: [
      'Automatic traceability matrix generation',
      'Change impact analysis with affected component list',
      'Cross-reference validation between requirements and tests',
      'Regression scope minimization',
    ],
    icon: Grid3x3,
    category: 'Functional',
    executionSpeed: 'Fast',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'load',
    num: '04',
    shortName: 'Load',
    fullName: 'Load & Scale Testing',
    tagline: 'Distributed load & predictive performance modeling',
    description:
      'TestForge simulates thousands of concurrent users across distributed agents. Predictive performance modeling forecasts how your application will behave under traffic spikes — before they happen. Auto-scaling validation ensures your infrastructure responds correctly.',
    metrics: ['10K+ RPS', 'Predictive modeling', 'Distributed agents'],
    features: [
      'Distributed load generation across multiple regions',
      'Predictive traffic modeling based on historical patterns',
      'Database connection pool stress testing',
      'Auto-scaling trigger validation',
      'Latency percentile analysis (p50, p95, p99)',
    ],
    icon: Gauge,
    category: 'Performance',
    executionSpeed: 'Medium',
    coverageDepth: 'Broad',
    aiEnhancement: 'Full',
  },
  {
    id: 'predictive',
    num: '05',
    shortName: 'Predictive',
    fullName: 'Predictive Testing',
    tagline: 'ML defect prediction & risk scoring',
    description:
      'Using machine learning models trained on millions of test outcomes, Predictive Testing identifies which parts of your codebase are most likely to contain defects — before tests even run. Risk scores prioritize testing effort where it matters most.',
    metrics: ['87% accuracy', 'Risk scoring', 'ML-powered'],
    features: [
      'Pre-code defect probability scoring',
      'Test prioritization based on risk heatmaps',
      'Historical failure pattern analysis',
      'Code complexity correlation with defect likelihood',
    ],
    icon: Brain,
    category: 'Intelligent',
    executionSpeed: 'Fast',
    coverageDepth: 'Targeted',
    aiEnhancement: 'Full',
  },
  {
    id: 'security',
    num: '06',
    shortName: 'Security',
    fullName: 'Security Testing',
    tagline: 'SAST, DAST, AI fuzzing — 4x coverage improvement',
    description:
      "Security Testing combines static analysis (SAST), dynamic analysis (DAST), and AI-powered fuzzing to uncover vulnerabilities across your entire stack. TestForge's AI fuzzer generates intelligent malicious inputs that traditional tools miss — delivering 4x the vulnerability coverage.",
    metrics: ['4x coverage', 'AI fuzzing', 'SAST + DAST'],
    features: [
      'Static Application Security Testing (SAST)',
      'Dynamic Application Security Testing (DAST)',
      'AI-powered intelligent fuzzing',
      'OWASP Top 10 compliance validation',
      'Secret and credential leak detection',
      'Dependency vulnerability scanning',
    ],
    icon: Shield,
    category: 'Security',
    executionSpeed: 'Medium',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'visual',
    num: '07',
    shortName: 'Visual',
    fullName: 'Visual Regression Testing',
    tagline: 'AI computer vision comparison — pixel-perfect',
    description:
      'Visual Regression Testing uses AI computer vision to detect UI changes — intentional and accidental. Screenshots are captured across breakpoints, devices, and browsers, then compared with pixel-level precision. Even a 1px shift gets caught.',
    metrics: ['Pixel-perfect', 'Multi-device', 'AI vision'],
    features: [
      'Screenshot comparison across all breakpoints',
      'AI-powered visual diff highlighting',
      'Component-level isolation detection',
      'Cross-browser visual consistency checks',
      'Baseline management with approval workflows',
    ],
    icon: Eye,
    category: 'Visual',
    executionSpeed: 'Fast',
    coverageDepth: 'Surface',
    aiEnhancement: 'Full',
  },
  {
    id: 'a11y',
    num: '08',
    shortName: 'A11y',
    fullName: 'Accessibility Testing',
    tagline: 'WCAG compliance validation — 57% automation coverage',
    description:
      'Accessibility Testing validates WCAG 2.1 AA compliance across your entire application. Automated checks cover 57% of WCAG criteria — including color contrast, keyboard navigation, screen reader compatibility, and focus management.',
    metrics: ['57% auto', 'WCAG 2.1', 'AA compliance'],
    features: [
      'Color contrast ratio validation (WCAG AA/AAA)',
      'Keyboard navigation flow testing',
      'Screen reader output verification',
      'Focus trap and order detection',
      'ARIA attribute validation',
      'Automated remediation suggestions',
    ],
    icon: Accessibility,
    category: 'Compliance',
    executionSpeed: 'Fast',
    coverageDepth: 'Deep',
    aiEnhancement: 'Partial',
  },
  {
    id: 'chaos',
    num: '09',
    shortName: 'Chaos',
    fullName: 'Chaos Engineering',
    tagline: 'RL-driven fault injection — +26.5% fault detection',
    description:
      'Chaos Engineering uses reinforcement learning to intelligently inject faults into your system — network delays, service failures, resource exhaustion. Unlike random chaos, RL-driven injection targets the weaknesses most likely to cause cascading failures.',
    metrics: ['+26.5% detection', 'RL-driven', 'Fault injection'],
    features: [
      'Reinforcement learning-driven fault injection',
      'Network latency and partition simulation',
      'Service dependency failure testing',
      'Resource exhaustion scenarios',
      'Cascading failure detection',
      'Automatic recovery validation',
    ],
    icon: CloudLightning,
    category: 'Resilience',
    executionSpeed: 'Slow',
    coverageDepth: 'Broad',
    aiEnhancement: 'Full',
  },
  {
    id: 'mutation',
    num: '10',
    shortName: 'Mutation',
    fullName: 'Mutation Testing',
    tagline: 'Test quality assessment via artificial faults',
    description:
      "Mutation Testing evaluates the quality of your test suite by introducing small artificial faults (mutations) into your code. If your tests catch the mutation, they're strong. If they don't, the mutation survives — revealing weak test coverage.",
    metrics: ['Mutation score', 'Test quality', 'Artificial faults'],
    features: [
      'Automatic mutation generation (conditionals, boundaries, arithmetic)',
      'Mutation score calculation per test suite',
      'Survivor analysis — identifying untested code paths',
      'Test strength ranking and recommendations',
      'Equivalent mutant detection',
    ],
    icon: Dna,
    category: 'Quality',
    executionSpeed: 'Slow',
    coverageDepth: 'Code-level',
    aiEnhancement: 'Full',
  },
  {
    id: 'property',
    num: '11',
    shortName: 'Property',
    fullName: 'Property-Based Testing',
    tagline: 'Invariant validation with intelligent input generation',
    description:
      'Property-Based Testing validates that your code maintains invariants across thousands of automatically generated inputs. Instead of testing specific examples, you define properties — and TestForge generates edge cases that would never occur to a human.',
    metrics: ['1000+ inputs', 'Invariant validation', 'Auto-generation'],
    features: [
      'Property definition and invariant specification',
      'Intelligent input generation (including edge cases)',
      'Shrinking — minimal failing case identification',
      'Cross-property interaction testing',
      'Regression property validation',
    ],
    icon: CheckCircle,
    category: 'Functional',
    executionSpeed: 'Medium',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'contract',
    num: '12',
    shortName: 'Contract',
    fullName: 'Contract Testing',
    tagline: 'Microservice API contract validation',
    description:
      'Contract Testing ensures your microservices honor their API contracts — both as providers and consumers. When a service changes, TestForge validates that all consumer expectations are still met. Breakages are caught before deployment, not in production.',
    metrics: ['Contract validation', 'Consumer-driven', 'Breakage prevention'],
    features: [
      'Provider and consumer contract validation',
      'OpenAPI / GraphQL schema compliance',
      'Pact-compatible contract testing',
      'Breaking change detection with impact analysis',
      'Consumer expectation mapping',
    ],
    icon: FileSignature,
    category: 'Integration',
    executionSpeed: 'Fast',
    coverageDepth: 'Interface',
    aiEnhancement: 'Partial',
  },
  {
    id: 'supply-chain',
    num: '14',
    shortName: 'Supply Chain',
    fullName: 'Supply Chain Audit',
    tagline: 'CVE database, dependency scanning, fix versions',
    description: 'Cross-references all dependencies against known CVE databases. Flags vulnerable packages with severity ratings, recommended fix versions, and exploitability assessments.',
    metrics: ['CVE Detection', 'Fix Versions', 'Severity Rating'],
    features: ['Known vulnerability database lookup', 'Fix version recommendations', 'Critical/High/Medium/Low classification', 'Exploitability assessment'],
    icon: 'shield', category: 'Security', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Full',
  },
  {
    id: 'n-plus-one',
    num: '15',
    shortName: 'N+1 Queries',
    fullName: 'N+1 Query Detection',
    tagline: 'Database performance, loop detection, eager loading',
    description: 'Scans for database queries inside loops. Detects missing eager loading, unoptimized joins, and potential N+1 patterns that cause exponential performance degradation.',
    metrics: ['Loop Detection', 'Eager Loading', 'Query Optimization'],
    features: ['ORM query loop detection', 'Missing eager loading identification', 'Performance impact estimation', 'Fix suggestions with code examples'],
    icon: 'zap', category: 'Performance', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Full',
  },
  {
    id: 'dead-code',
    num: '16',
    shortName: 'Dead Code',
    fullName: 'Dead Code Analysis',
    tagline: 'Unused dependencies, dead exports, tree-shaking',
    description: 'Identifies imported but unused dependencies and potentially dead exports. Estimates bundle size savings from removing unused code.',
    metrics: ['Unused Deps', 'Dead Exports', 'Size Savings'],
    features: ['Unused dependency detection', 'Dead export identification', 'Bundle size savings estimation', 'Safe removal recommendations'],
    icon: 'trash', category: 'Cleanup', executionSpeed: 'Fast', coverageDepth: 'Medium', aiEnhancement: 'Auto',
  },
  {
    id: 'license',
    num: '17',
    shortName: 'License',
    fullName: 'License Compliance',
    tagline: 'GPL detection, copyleft risks, compliance audit',
    description: 'Checks all dependencies for license type. Flags GPL/copyleft risks. Ensures compliance with your organization open source policy.',
    metrics: ['License Type', 'Copyleft Risk', 'Compliance Score'],
    features: ['License type detection', 'GPL/copyleft risk flagging', 'Compliance report', 'Policy enforcement suggestions'],
    icon: 'file-text', category: 'Compliance', executionSpeed: 'Fast', coverageDepth: 'Medium', aiEnhancement: 'Auto',
  },
  {
    id: 'dora',
    num: '18',
    shortName: 'DORA',
    fullName: 'DORA Metrics',
    tagline: 'Deployment frequency, lead time, MTTR, change fail rate',
    description: 'Estimates the four DORA metrics from CI/CD configuration and code patterns. Deployment Frequency, Lead Time for Changes, Mean Time to Recovery, and Change Failure Rate.',
    metrics: ['Deploy Freq', 'Lead Time', 'MTTR', 'Change Fail %'],
    features: ['CI/CD configuration analysis', 'Deployment frequency estimation', 'Lead time calculation', 'MTTR and change failure rate prediction', 'Elite/High/Medium/Low classification'],
    icon: 'trending-up', category: 'DevOps', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Full',
  },
  {
    id: 'owasp',
    num: '19',
    shortName: 'OWASP',
    fullName: 'OWASP Top 10 Coverage',
    tagline: 'Security standards, gap analysis, compliance mapping',
    description: 'Maps all security findings to OWASP Top 10 categories. Reports coverage percentage and identifies gaps in security testing.',
    metrics: ['Coverage %', 'Covered Categories', 'Missing Categories'],
    features: ['OWASP Top 10 mapping', 'Coverage percentage', 'Gap analysis', 'Security posture assessment'],
    icon: 'shield', category: 'Security', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Full',
  },
  {
    id: 'edge',
    num: '20',
    shortName: 'Edge',
    fullName: 'Edge Case Generation',
    tagline: 'AI fuzzing, pairwise testing, boundary analysis',
    description:
      'Edge Case Generation is the final safety net. AI fuzzing produces unexpected inputs. Pairwise testing covers all parameter combinations. Boundary analysis tests every limit. Together, they catch the bugs that only appear at 3 AM on a Tuesday.',
    metrics: ['AI fuzzing', 'Pairwise', 'Boundary analysis'],
    features: [
      'AI-powered intelligent fuzzing with context awareness',
      'Pairwise combination testing for multi-parameter functions',
      'Boundary value analysis (min, max, just-beyond)',
      'Negative testing with invalid input patterns',
      'State machine edge case traversal',
    ],
    icon: GitBranch,
    category: 'Functional',
    executionSpeed: 'Medium',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'agentic',
    num: '21',
    shortName: 'Agentic Scale',
    fullName: 'Agentic Scale Prediction',
    tagline: 'AI agent simulation, scale prediction, failure patterns',
    description: 'World first — simulates thousands of AI agents hitting your API simultaneously. Predicts failure patterns, bottlenecks, and cascading failures unique to agentic workloads.',
    metrics: ['Max Agents', 'Bottleneck', 'Failure Patterns', 'Recommendations'],
    features: ['Agentic traffic simulation', 'Max concurrent agent prediction', 'Bottleneck identification', 'Failure pattern analysis', '8 specific resilience recommendations'],
    icon: 'cpu', category: 'Strategy', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Full',
  },
];

export const comparisonData = [
  {
    dimension: 'Scope Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Vision & Goal Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Feature Matrix Testing',
    testforge: true,
    testsprite: true,
    traditional: false,
  },
  {
    dimension: 'Load & Scale Testing',
    testforge: true,
    testsprite: true,
    traditional: true,
  },
  {
    dimension: 'Predictive Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Security Testing',
    testforge: true,
    testsprite: true,
    traditional: true,
  },
  {
    dimension: 'Visual Regression',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Accessibility Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Chaos Engineering',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Mutation Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Property-Based Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Contract Testing',
    testforge: true,
    testsprite: true,
    traditional: false,
  },
  {
    dimension: 'Edge Case Generation',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Supply Chain Audit',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'N+1 Query Detection',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Dead Code Analysis',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'License Compliance',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'DORA Metrics',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'OWASP Coverage',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Agentic Scale Prediction',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Agentic Scale Prediction',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
];
