import type { LucideIcon } from 'lucide-react';
import {
  ScanLine,
  Target,
  Grid3x3,
  Gauge,
  Brain,
  Shield,
  Eye,
  Accessibility,
  CloudLightning,
  Dna,
  CheckCircle,
  FileSignature,
  GitBranch,
  Zap,
  Trash2,
  FileText,
  TrendingUp,
  Cpu,
  FlaskConical,
} from 'lucide-react';

export interface Dimension {
  id: string;
  num: string;
  shortName: string;
  fullName: string;
  tagline: string;
  description: string;
  metrics: string[];
  features: string[];
  icon: LucideIcon;
  category: string;
  executionSpeed: string;
  coverageDepth: string;
  aiEnhancement: string;
}

export const dimensions: Dimension[] = [
  {
    id: 'scope',
    num: '01',
    shortName: 'Scope',
    fullName: 'Scope Testing',
    tagline: 'Requirements coverage & boundary validation',
    description:
      'Scope Testing ensures every requirement is covered by at least one test case. TestForge parses your PRDs, user stories, and acceptance criteria — then maps them against your codebase to identify gaps. Boundary validation checks edge conditions, null inputs, and limit values that human testers often miss.',
    metrics: ['98% coverage', 'Auto PRD parsing', 'Boundary detection'],
    features: [
      'Automatic requirements extraction from PRDs and issues',
      'Coverage gap identification with risk-weighted prioritization',
      'Boundary value analysis for every input parameter',
      'Requirement-to-test traceability matrix',
    ],
    icon: ScanLine,
    category: 'Functional',
    executionSpeed: 'Fast',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'vision',
    num: '02',
    shortName: 'Vision',
    fullName: 'Vision & Goal Testing',
    tagline: 'Business goal alignment & outcome prediction',
    description:
      "Does your code actually achieve the business goal? Vision & Goal Testing measures alignment between implemented features and intended outcomes. TestForge predicts user behavior patterns and validates that the code produces the desired business results — not just technically correct outputs.",
    metrics: ['94% alignment', 'Outcome prediction', 'Goal tracking'],
    features: [
      'Business goal extraction from product documentation',
      'Feature-to-outcome mapping and scoring',
      'User journey validation against intended paths',
      'ROI impact estimation for each feature',
    ],
    icon: Target,
    category: 'Functional',
    executionSpeed: 'Medium',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'matrix',
    num: '03',
    shortName: 'Matrix',
    fullName: 'Feature Matrix Testing',
    tagline: 'Traceability matrices & impact analysis',
    description:
      'Feature Matrix Testing automatically generates and maintains traceability matrices linking requirements, tests, code, and deployments. When a change occurs, impact analysis identifies every affected component — preventing regression surprises.',
    metrics: ['Auto-generated', 'Impact analysis', 'Full traceability'],
    features: [
      'Automatic traceability matrix generation',
      'Change impact analysis with affected component list',
      'Cross-reference validation between requirements and tests',
      'Regression scope minimization',
    ],
    icon: Grid3x3,
    category: 'Functional',
    executionSpeed: 'Fast',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'load',
    num: '04',
    shortName: 'Load Patterns',
    fullName: 'Load & Scale Pattern Analysis',
    tagline: 'Detects the code patterns your service needs to survive traffic',
    description:
      "Scans for the patterns your code needs to survive load — rate limits on public endpoints, caching layers in hot paths, queue/backpressure handling, connection-pool sizing, pagination on list reads. TestForge surfaces the static gaps so your next k6 / Locust run finds fewer surprises.",
    metrics: ['Rate-limit detection', 'Cache detection', 'Queue/backpressure'],
    features: [
      'Rate-limit middleware detection (express-rate-limit, fastify/rate-limit)',
      'Cache-layer detection (Redis, in-memory, HTTP caching)',
      'Queue / backpressure handling detection',
      'Connection-pool configuration scan',
      'Pagination presence on list endpoints',
      'Pairs naturally with k6 / Locust for live load runs',
    ],
    icon: Gauge,
    category: 'Performance',
    executionSpeed: 'Fast',
    coverageDepth: 'Deep',
    aiEnhancement: 'Auto',
  },
  {
    id: 'predictive',
    num: '05',
    shortName: 'Predictive',
    fullName: 'Predictive Risk Scoring',
    tagline: 'Risk score per file from complexity + churn signals',
    description:
      "Each file gets a risk score combining AST-derived cyclomatic complexity (McCabe), function length, parameter counts, dependency density, and — when git history is available — change-frequency churn. The output is a ranked heatmap so reviewers spend deep-review time on the files that earn it.",
    metrics: ['Cyclomatic complexity', 'Risk heatmap', 'Per-file scoring'],
    features: [
      'AST cyclomatic complexity per function (McCabe)',
      'Function length and parameter-count thresholds',
      'Dependency density per module',
      'Optional change-frequency signals from git',
      'Ranked risk heatmap for review prioritization',
    ],
    icon: Brain,
    category: 'Intelligent',
    executionSpeed: 'Fast',
    coverageDepth: 'Per-file',
    aiEnhancement: 'Auto',
  },
  {
    id: 'security',
    num: '06',
    shortName: 'Security',
    fullName: 'Security (SAST + Taint Tracking)',
    tagline: 'Babel AST + taint flow across the OWASP Top 10',
    description:
      "Static security analysis using Babel AST + taint tracking. TestForge traces tainted sources (user input from req.params, req.body, req.query) through function calls to sensitive sinks (SQL, eval, exec, fs, child_process, innerHTML). Findings map directly to OWASP Top 10 categories. Pairs naturally with a runtime DAST tool — TestForge handles the static layer.",
    metrics: ['AST + taint', 'OWASP-mapped', 'Pre-merge'],
    features: [
      'SQL / NoSQL injection via tainted-input flow',
      'eval / Function() / vm.runIn* sink detection',
      'XSS sinks: innerHTML, dangerouslySetInnerHTML, document.write',
      'Hardcoded secret patterns (API keys, JWT, AWS keys)',
      'CORS misconfig (wildcard origin + credentials true)',
      'OWASP Top 10 coverage % per category',
    ],
    icon: Shield,
    category: 'Security',
    executionSpeed: 'Fast',
    coverageDepth: 'Deep',
    aiEnhancement: 'Auto',
  },
  {
    id: 'visual',
    num: '07',
    shortName: 'Visual',
    fullName: 'Visual Regression Testing',
    tagline: 'AI computer vision comparison — pixel-perfect',
    description:
      'Visual Regression Testing uses AI computer vision to detect UI changes — intentional and accidental. Screenshots are captured across breakpoints, devices, and browsers, then compared with pixel-level precision. Even a 1px shift gets caught.',
    metrics: ['Pixel-perfect', 'Multi-device', 'AI vision'],
    features: [
      'Screenshot comparison across all breakpoints',
      'AI-powered visual diff highlighting',
      'Component-level isolation detection',
      'Cross-browser visual consistency checks',
      'Baseline management with approval workflows',
    ],
    icon: Eye,
    category: 'Visual',
    executionSpeed: 'Fast',
    coverageDepth: 'Surface',
    aiEnhancement: 'Full',
  },
  {
    id: 'a11y',
    num: '08',
    shortName: 'A11y',
    fullName: 'Accessibility Testing',
    tagline: 'WCAG compliance validation — 57% automation coverage',
    description:
      'Accessibility Testing validates WCAG 2.1 AA compliance across your entire application. Automated checks cover 57% of WCAG criteria — including color contrast, keyboard navigation, screen reader compatibility, and focus management.',
    metrics: ['57% auto', 'WCAG 2.1', 'AA compliance'],
    features: [
      'Color contrast ratio validation (WCAG AA/AAA)',
      'Keyboard navigation flow testing',
      'Screen reader output verification',
      'Focus trap and order detection',
      'ARIA attribute validation',
      'Automated remediation suggestions',
    ],
    icon: Accessibility,
    category: 'Compliance',
    executionSpeed: 'Fast',
    coverageDepth: 'Deep',
    aiEnhancement: 'Partial',
  },
  {
    id: 'chaos',
    num: '09',
    shortName: 'Chaos',
    fullName: 'Resilience Pattern Detection',
    tagline: 'The patterns your code needs to survive partial failures',
    description:
      "Scans for the patterns your code needs to survive partial failures: retry-with-backoff, circuit breakers, request timeouts, idempotency keys, graceful degradation. Flags critical I/O paths missing these defenses. Pairs with runtime chaos tooling (Gremlin, Litmus, Chaos Mesh) — TestForge surfaces the static gaps before you simulate the failure.",
    metrics: ['Retry patterns', 'Circuit-breakers', 'Timeouts'],
    features: [
      'Retry-with-backoff pattern detection',
      'Circuit-breaker library usage (opossum, polly, hystrix)',
      'Request timeout configuration scan',
      'Idempotency-key handling on POST/PUT endpoints',
      'I/O paths missing resilience guards flagged',
      'Pairs with runtime chaos tools for live validation',
    ],
    icon: CloudLightning,
    category: 'Resilience',
    executionSpeed: 'Fast',
    coverageDepth: 'Deep',
    aiEnhancement: 'Auto',
  },
  {
    id: 'mutation',
    num: '10',
    shortName: 'Mutation Estimate',
    fullName: 'Mutation-Score Estimate',
    tagline: 'Heuristic mutation score in seconds, not minutes',
    description:
      "Full mutation testing (Stryker, Pitest) is the gold standard but takes minutes per file. TestForge estimates the mutation score in seconds by analyzing assertion density, branch coverage in test files, and the test-to-source ratio. Not as authoritative as a real Stryker run — close enough to flag weak suites pre-merge and pair with the heavier tool in CI.",
    metrics: ['Score estimate', 'Per-file', 'Pre-merge'],
    features: [
      'Estimated mutation score per source file',
      'Assertion-density signals from the test files',
      'Branch coverage signals',
      'Surfaces suites with low mutation resilience',
      'Pairs naturally with Stryker / Pitest for confirmation',
    ],
    icon: Dna,
    category: 'Quality',
    executionSpeed: 'Fast',
    coverageDepth: 'Per-file',
    aiEnhancement: 'Auto',
  },
  {
    id: 'property',
    num: '11',
    shortName: 'Property',
    fullName: 'Property-Based Testing',
    tagline: 'Invariant validation with intelligent input generation',
    description:
      'Property-Based Testing validates that your code maintains invariants across thousands of automatically generated inputs. Instead of testing specific examples, you define properties — and TestForge generates edge cases that would never occur to a human.',
    metrics: ['1000+ inputs', 'Invariant validation', 'Auto-generation'],
    features: [
      'Property definition and invariant specification',
      'Intelligent input generation (including edge cases)',
      'Shrinking — minimal failing case identification',
      'Cross-property interaction testing',
      'Regression property validation',
    ],
    icon: CheckCircle,
    category: 'Functional',
    executionSpeed: 'Medium',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'contract',
    num: '12',
    shortName: 'Contract',
    fullName: 'Contract Testing',
    tagline: 'Microservice API contract validation',
    description:
      'Contract Testing ensures your microservices honor their API contracts — both as providers and consumers. When a service changes, TestForge validates that all consumer expectations are still met. Breakages are caught before deployment, not in production.',
    metrics: ['Contract validation', 'Consumer-driven', 'Breakage prevention'],
    features: [
      'Provider and consumer contract validation',
      'OpenAPI / GraphQL schema compliance',
      'Pact-compatible contract testing',
      'Breaking change detection with impact analysis',
      'Consumer expectation mapping',
    ],
    icon: FileSignature,
    category: 'Integration',
    executionSpeed: 'Fast',
    coverageDepth: 'Interface',
    aiEnhancement: 'Partial',
  },
  {
    id: 'test-quality',
    num: '13',
    shortName: 'Test Quality',
    fullName: 'Test Quality Analysis',
    tagline: 'Finds the ghost tests in your suite',
    description:
      "Most test suites contain ghost tests that look green but assert nothing. TestForge walks every parseable test file and flags it.skip / xit / it.todo (rot risk), it.only / fit (silently kills sibling tests in CI), empty test bodies, and tests with zero recognized assertions across 8 frameworks.",
    metrics: ['Skip detection', 'Focus detection', '8 frameworks'],
    features: [
      'AST-aware detection of it.skip / xit / it.todo',
      'it.only / fit detection (these silently skip sibling tests)',
      'Tests with no recognized assertion call',
      'Empty test bodies (comments-only)',
      'Tests importing nothing project-relative',
      'Supports Jest, Vitest, Mocha, AVA, Tap, node:test, Testing Library, Chai',
    ],
    icon: FlaskConical,
    category: 'Quality',
    executionSpeed: 'Fast',
    coverageDepth: 'Per-file',
    aiEnhancement: 'Auto',
  },
  {
    id: 'supply-chain',
    num: '14',
    shortName: 'Supply Chain',
    fullName: 'Supply Chain Audit',
    tagline: 'CVE database, dependency scanning, fix versions',
    description: 'Cross-references all dependencies against known CVE databases. Flags vulnerable packages with severity ratings, recommended fix versions, and exploitability assessments.',
    metrics: ['CVE Detection', 'Fix Versions', 'Severity Rating'],
    features: ['Known vulnerability database lookup', 'Fix version recommendations', 'Critical/High/Medium/Low classification', 'Exploitability assessment'],
    icon: Shield, category: 'Security', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Full',
  },
  {
    id: 'n-plus-one',
    num: '15',
    shortName: 'N+1 Queries',
    fullName: 'N+1 Query Detection',
    tagline: 'Database performance, loop detection, eager loading',
    description: 'Scans for database queries inside loops. Detects missing eager loading, unoptimized joins, and potential N+1 patterns that cause exponential performance degradation.',
    metrics: ['Loop Detection', 'Eager Loading', 'Query Optimization'],
    features: ['ORM query loop detection', 'Missing eager loading identification', 'Performance impact estimation', 'Fix suggestions with code examples'],
    icon: Zap, category: 'Performance', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Full',
  },
  {
    id: 'dead-code',
    num: '16',
    shortName: 'Dead Code',
    fullName: 'Dead Code Analysis',
    tagline: 'Unused dependencies, dead exports, tree-shaking',
    description: 'Identifies imported but unused dependencies and potentially dead exports. Estimates bundle size savings from removing unused code.',
    metrics: ['Unused Deps', 'Dead Exports', 'Size Savings'],
    features: ['Unused dependency detection', 'Dead export identification', 'Bundle size savings estimation', 'Safe removal recommendations'],
    icon: Trash2, category: 'Cleanup', executionSpeed: 'Fast', coverageDepth: 'Medium', aiEnhancement: 'Auto',
  },
  {
    id: 'license',
    num: '17',
    shortName: 'License',
    fullName: 'License Compliance',
    tagline: 'GPL detection, copyleft risks, compliance audit',
    description: 'Checks all dependencies for license type. Flags GPL/copyleft risks. Ensures compliance with your organization open source policy.',
    metrics: ['License Type', 'Copyleft Risk', 'Compliance Score'],
    features: ['License type detection', 'GPL/copyleft risk flagging', 'Compliance report', 'Policy enforcement suggestions'],
    icon: FileText, category: 'Compliance', executionSpeed: 'Fast', coverageDepth: 'Medium', aiEnhancement: 'Auto',
  },
  {
    id: 'dora',
    num: '18',
    shortName: 'DORA',
    fullName: 'DORA Metrics',
    tagline: 'Deployment frequency, lead time, MTTR, change fail rate',
    description: 'Estimates the four DORA metrics from CI/CD configuration and code patterns. Deployment Frequency, Lead Time for Changes, Mean Time to Recovery, and Change Failure Rate.',
    metrics: ['Deploy Freq', 'Lead Time', 'MTTR', 'Change Fail %'],
    features: ['CI/CD configuration analysis', 'Deployment frequency estimation', 'Lead time calculation', 'MTTR and change failure rate prediction', 'Elite/High/Medium/Low classification'],
    icon: TrendingUp, category: 'DevOps', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Full',
  },
  {
    id: 'owasp',
    num: '19',
    shortName: 'OWASP',
    fullName: 'OWASP Top 10 Coverage',
    tagline: 'Security standards, gap analysis, compliance mapping',
    description: 'Maps all security findings to OWASP Top 10 categories. Reports coverage percentage and identifies gaps in security testing.',
    metrics: ['Coverage %', 'Covered Categories', 'Missing Categories'],
    features: ['OWASP Top 10 mapping', 'Coverage percentage', 'Gap analysis', 'Security posture assessment'],
    icon: Shield, category: 'Security', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Full',
  },
  {
    id: 'edge',
    num: '20',
    shortName: 'Edge',
    fullName: 'Edge Case Generation',
    tagline: 'AI fuzzing, pairwise testing, boundary analysis',
    description:
      'Edge Case Generation is the final safety net. AI fuzzing produces unexpected inputs. Pairwise testing covers all parameter combinations. Boundary analysis tests every limit. Together, they catch the bugs that only appear at 3 AM on a Tuesday.',
    metrics: ['AI fuzzing', 'Pairwise', 'Boundary analysis'],
    features: [
      'AI-powered intelligent fuzzing with context awareness',
      'Pairwise combination testing for multi-parameter functions',
      'Boundary value analysis (min, max, just-beyond)',
      'Negative testing with invalid input patterns',
      'State machine edge case traversal',
    ],
    icon: GitBranch,
    category: 'Functional',
    executionSpeed: 'Medium',
    coverageDepth: 'Deep',
    aiEnhancement: 'Full',
  },
  {
    id: 'agentic',
    num: '21',
    shortName: 'Agentic Scale',
    fullName: 'Agentic Traffic Risk Analysis',
    tagline: 'Code patterns that break under agentic concurrency',
    description:
      "AI agents hit APIs in patterns humans don't — extreme parallelism, retry storms, unpaginated bulk reads, no caching. TestForge flags the code paths most likely to degrade under this load profile so you fix them before agentic traffic finds them.",
    metrics: ['Concurrency risk', 'Unbounded queries', 'Idempotency gaps'],
    features: [
      'Endpoints without rate limits flagged for agentic risk',
      'Unbounded list queries (missing LIMIT / pagination)',
      'Sync I/O on high-traffic paths',
      'Missing idempotency on POST endpoints',
      'Retry-storm risk in client code',
      'Pairs with load-testing tools for live validation',
    ],
    icon: Cpu, category: 'Strategy', executionSpeed: 'Fast', coverageDepth: 'Deep', aiEnhancement: 'Auto',
  },
];

export const comparisonData = [
  {
    dimension: 'Scope Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Vision & Goal Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Feature Matrix Testing',
    testforge: true,
    testsprite: true,
    traditional: false,
  },
  {
    dimension: 'Load & Scale Testing',
    testforge: true,
    testsprite: true,
    traditional: true,
  },
  {
    dimension: 'Predictive Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Security Testing',
    testforge: true,
    testsprite: true,
    traditional: true,
  },
  {
    dimension: 'Visual Regression',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Accessibility Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Chaos Engineering',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Mutation Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Property-Based Testing',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Contract Testing',
    testforge: true,
    testsprite: true,
    traditional: false,
  },
  {
    dimension: 'Test Quality Analysis',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Edge Case Generation',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Supply Chain Audit',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'N+1 Query Detection',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Dead Code Analysis',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'License Compliance',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'DORA Metrics',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'OWASP Coverage',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
  {
    dimension: 'Agentic Scale Prediction',
    testforge: true,
    testsprite: false,
    traditional: false,
  },
];
