#!/usr/bin/env bash
# Register the TestForge flywheel as a Hermes scheduled job.
#
# Hermes runs cron scripts from ~/.hermes/scripts/, so we drop a thin launcher
# there that execs the repo's cycle.mjs in place (keeping it self-contained and
# shippable with the repo — the launcher is the only thing outside the tree).
# The job runs in --no-agent mode: cycle.mjs *is* the job, and its stdout (the
# Telegram digest) is delivered verbatim. cycle.mjs calls the brain itself
# (claude -p) — Hermes is pure scheduling + delivery here.
#
# Usage:
#   hermes/register-hermes.sh                 # print what it would do (dry)
#   hermes/register-hermes.sh --create        # actually create the Hermes job
#   SCHEDULE='0 9 * * *' DELIVER=telegram hermes/register-hermes.sh --create
#
# Env: SCHEDULE (default 'every 6h')  DELIVER (default 'telegram')  NAME (default 'TestForge flywheel')

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"

SCHEDULE="${SCHEDULE:-every 6h}"
DELIVER="${DELIVER:-telegram}"
NAME="${NAME:-TestForge flywheel}"

HERMES_BIN="$(command -v hermes || echo "$HOME/.local/bin/hermes")"
SCRIPTS_DIR="$HOME/.hermes/scripts"
LAUNCHER="$SCRIPTS_DIR/testforge-flywheel.sh"
NODE_BIN="$(command -v node || echo node)"

write_launcher() {
  mkdir -p "$SCRIPTS_DIR"
  cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# AUTO-GENERATED by testforge/hermes/register-hermes.sh — runs one flywheel cycle.
# Edit the flywheel in the repo, not here; re-run register-hermes.sh to refresh.
exec "$NODE_BIN" "$REPO_ROOT/hermes/cycle.mjs" "\$@"
EOF
  chmod +x "$LAUNCHER"
  echo "wrote launcher → $LAUNCHER"
}

CRON_CMD=( "$HERMES_BIN" cron create "$SCHEDULE"
  --no-agent
  --script "testforge-flywheel.sh"
  --deliver "$DELIVER"
  --name "$NAME" )

if [[ "${1:-}" == "--create" ]]; then
  write_launcher
  echo "creating Hermes job:"
  printf '  %q ' "${CRON_CMD[@]}"; echo
  "${CRON_CMD[@]}"
  echo
  echo "Done. Inspect with:  $HERMES_BIN cron list"
  echo "Run once now with:   $HERMES_BIN cron tick   (or: node $REPO_ROOT/hermes/cycle.mjs)"
else
  echo "DRY RUN (pass --create to apply). Would:"
  echo "  1. write launcher → $LAUNCHER  (execs $REPO_ROOT/hermes/cycle.mjs)"
  echo "  2. register:"
  printf '       %q ' "${CRON_CMD[@]}"; echo
  echo
  echo "Schedule='$SCHEDULE'  Deliver='$DELIVER'  Name='$NAME'  (override via env vars)"
fi
