#!/usr/bin/env bash
# Register the TestForge flywheel as a Hermes scheduled job.
#
# Hermes runs cron scripts from ~/.hermes/scripts/, so we drop a thin launcher
# there that execs the repo's cycle.mjs in place (keeping it self-contained and
# shippable with the repo — the launcher is the only thing outside the tree).
# The job runs in --no-agent mode: cycle.mjs *is* the job, and its stdout (the
# Telegram digest) is delivered verbatim. cycle.mjs calls the brain itself
# (claude -p) — Hermes is pure scheduling + delivery here.
#
# Usage:
#   hermes/register-hermes.sh                 # print what it would do (dry)
#   hermes/register-hermes.sh --create        # actually create the Hermes job
#   SCHEDULE='0 9 * * *' DELIVER=telegram hermes/register-hermes.sh --create
#
# Env: SCHEDULE (default 'every 6h')  DELIVER (default 'telegram')  NAME (default 'TestForge flywheel')

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"

SCHEDULE="${SCHEDULE:-0 9 * * *}"   # daily 09:00 — conservative; override via env
DELIVER="${DELIVER:-telegram}"
NAME="${NAME:-TestForge flywheel}"

# The scheduled ledger MUST live outside the git-tracked repo: cycle.mjs appends
# to it every run, and the in-repo hermes/ledger.md is tracked — unattended
# appends would dirty the working tree and could be clobbered by a `git pull`.
# Default to an Obsidian-readable note under the vault (off-repo), seeded once
# from the repo's committed ledger so history carries over. Override via $LEDGER.
LEDGER="${LEDGER:-$HOME/testforge/vault/notes/testforge-flywheel-ledger.md}"

# The brain (claude -p) needs Claude auth, but the hermes gateway runs in a
# stripped environment WITHOUT your interactive `claude login` session — a
# scheduled run hits "Not logged in". The fix is a long-lived OAuth token from
# `claude setup-token`, stored as CLAUDE_CODE_OAUTH_TOKEN in this off-repo,
# 0600, gitignored env-file. The launcher sources it before invoking the brain.
ENVFILE="${ENVFILE:-$HOME/.hermes/.testforge-flywheel.env}"

HERMES_BIN="$(command -v hermes || echo "$HOME/.local/bin/hermes")"
SCRIPTS_DIR="$HOME/.hermes/scripts"
LAUNCHER="$SCRIPTS_DIR/testforge-flywheel.sh"
NODE_BIN="$(command -v node || echo node)"

write_launcher() {
  mkdir -p "$SCRIPTS_DIR"
  # Seed the live ledger from the repo's committed one (once) so the scheduled
  # loop starts with this session's proposed/shipped history, not a blank slate.
  mkdir -p "$(dirname "$LEDGER")"
  if [[ ! -f "$LEDGER" ]]; then
    cp "$REPO_ROOT/hermes/ledger.md" "$LEDGER" 2>/dev/null \
      && echo "seeded live ledger → $LEDGER (from repo's committed ledger)" \
      || echo "note: could not seed $LEDGER; cycle.mjs will create it"
  fi
  # Create the auth env-file stub (0600) if absent, so there's a clear, secure
  # home for the OAuth token. NEVER write the token here — the user runs
  # `claude setup-token` and pastes it in. The file is off-repo + gitignored.
  if [[ ! -f "$ENVFILE" ]]; then
    ( umask 077; cat > "$ENVFILE" <<'STUB'
# TestForge flywheel — brain auth (off-repo, 0600, gitignored).
# Generate a long-lived token interactively:  claude setup-token
# then set it below (uncomment, paste the value):
# CLAUDE_CODE_OAUTH_TOKEN=sk-ant-oat01-...
STUB
    )
    chmod 600 "$ENVFILE"
    echo "wrote auth env-file stub → $ENVFILE (add CLAUDE_CODE_OAUTH_TOKEN via \`claude setup-token\`)"
  fi
  cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# AUTO-GENERATED by testforge/hermes/register-hermes.sh — runs one flywheel cycle.
# Edit the flywheel in the repo, not here; re-run register-hermes.sh to refresh.
# Source the off-repo auth env-file first: the hermes gateway runs without your
# interactive \`claude login\`, so the brain needs CLAUDE_CODE_OAUTH_TOKEN here.
[ -f "$ENVFILE" ] && set -a && . "$ENVFILE" && set +a
# TESTFORGE_LEDGER points OFF the git-tracked tree so scheduled appends don't
# dirty the repo (the in-repo hermes/ledger.md is the committed seed/history).
export TESTFORGE_LEDGER="$LEDGER"
exec "$NODE_BIN" "$REPO_ROOT/hermes/cycle.mjs" "\$@"
EOF
  chmod +x "$LAUNCHER"
  echo "wrote launcher → $LAUNCHER  (ledger: $LEDGER, auth: $ENVFILE)"
}

CRON_CMD=( "$HERMES_BIN" cron create "$SCHEDULE"
  --no-agent
  --script "testforge-flywheel.sh"
  --deliver "$DELIVER"
  --name "$NAME" )

if [[ "${1:-}" == "--create" ]]; then
  write_launcher
  echo "creating Hermes job:"
  printf '  %q ' "${CRON_CMD[@]}"; echo
  "${CRON_CMD[@]}"
  echo
  echo "Done. Inspect with:  $HERMES_BIN cron list"
  echo "Run once now with:   $HERMES_BIN cron tick   (or: node $REPO_ROOT/hermes/cycle.mjs)"
else
  echo "DRY RUN (pass --create to apply). Would:"
  echo "  1. write launcher → $LAUNCHER  (execs $REPO_ROOT/hermes/cycle.mjs)"
  echo "     ledger (off-repo, seeded from committed ledger) → $LEDGER"
  echo "  2. register:"
  printf '       %q ' "${CRON_CMD[@]}"; echo
  echo
  echo "Schedule='$SCHEDULE'  Deliver='$DELIVER'  Name='$NAME'  Ledger='$LEDGER'  (override via env vars)"
fi
