import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  CheckCircle2, FileJson, FileText, FileDown, Shield,
  RotateCcw
} from 'lucide-react';

interface ReportStepProps {
  results: any;
  onRestart: () => void;
}

function SeverityBadge({ severity }: { severity: string }) {
  const config: Record<string, string> = {
    critical: 'bg-[rgba(212,82,74,0.1)] text-[#D4524A]',
    high: 'bg-[rgba(232,125,58,0.1)] text-[#E87D3A]',
    medium: 'bg-[rgba(232,168,56,0.1)] text-[#E8A838]',
    low: 'bg-[rgba(90,143,94,0.1)] text-[#5A8F5E]',
  };
  return (
    <span className={`inline-flex px-2 py-0.5 rounded text-[11px] font-mono font-medium uppercase ${config[severity] || config.low}`}>
      {severity}
    </span>
  );
}

export default function ReportStep({ results, onRestart }: ReportStepProps) {
  const [expandedFinding, setExpandedFinding] = useState<number | null>(null);
  const [exportFormat, setExportFormat] = useState<string | null>(null);

  if (!results) {
    return (
      <div className="text-center py-12">
        <p className="text-[#6B6B6B]">No analysis results available.</p>
        <button onClick={onRestart} className="mt-4 text-[#5A8F5E] font-medium">Try again</button>
      </div>
    );
  }

  const { codebase = {}, security = {}, unit = {}, load = {}, accessibility = {} } = results;
  const overallScore = Math.round(
    (accessibility.score || 70) * 0.3 +
    Math.max(0, 100 - (security.critical || 0) * 20 - (security.high || 0) * 5) * 0.3 +
    Math.max(0, 100 - (load.maxUsers < 50 ? 30 : 0)) * 0.2 +
    (unit.coverage || 50) * 0.2
  );

  const scoreColor = overallScore >= 80 ? '#5A8F5E' : overallScore >= 50 ? '#E8A838' : '#D4524A';

  const handleExport = (format: string) => {
    setExportFormat(format);
    let content = '';
    let filename = `testforge-report.${format === 'json' ? 'json' : 'md'}`;
    let mimeType = 'text/plain';

    if (format === 'json') {
      content = JSON.stringify(results, null, 2);
      mimeType = 'application/json';
    } else if (format === 'markdown') {
      content = `# TestForge Analysis Report\n\n`;
      content += `**Repo:** ${results.repo || 'Unknown'}\n`;
      content += `**Branch:** ${results.branch || 'main'}\n`;
      content += `**Analyzed:** ${results.analyzedAt || new Date().toISOString()}\n\n`;
      content += `## Codebase\n- **Files:** ${codebase.totalFiles}\n- **Lines:** ${codebase.totalLines}\n- **Endpoints:** ${codebase.endpoints}\n- **Tech Stack:** ${(codebase.techStack || []).join(', ')}\n\n`;
      content += `## Security (${security.findings} findings)\n`;
      (security.items || []).forEach((f: any) => {
        content += `- **[${f.severity.toUpperCase()}]** ${f.title} — \`${f.filePath}:${f.lineNumber}\`\n`;
        if (f.fixSuggestion) content += `  - Fix: ${f.fixSuggestion}\n`;
      });
      content += `\n## Unit Tests\n- Coverage: ${unit.coverage}%\n- Test Files: ${unit.testFiles}\n- Frameworks: ${(unit.frameworks || []).join(', ')}\n\n`;
      content += `## Load Analysis\n- Max Users: ${load.maxUsers}\n- Rate Limiting: ${load.rateLimiting ? 'Yes' : 'No'}\n- Caching: ${load.caching ? 'Yes' : 'No'}\n\n`;
      content += `## Accessibility\n- Score: ${accessibility.score}/100\n- Issues: ${accessibility.issues}\n\n`;
      content += `---\n*Generated by TestForge AI*`;
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setExportFormat(null), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-[800px] mx-auto"
    >
      {/* Header */}
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-[#E8F0E8] rounded-full mb-4">
          <CheckCircle2 size={16} className="text-[#5A8F5E]" />
          <span className="font-mono text-xs text-[#5A8F5E] font-medium">ANALYSIS COMPLETE</span>
        </div>
        <h2 className="font-heading text-[28px] font-medium text-[#1A1A1A]">Test Report</h2>
        <p className="text-[#6B6B6B] mt-2">
          {results.repo && <span className="font-mono text-sm">{results.repo}</span>}
          {' · '}{codebase.totalFiles} files · {codebase.totalLines} lines
        </p>
      </div>

      {/* Score Card */}
      <div className="bg-white border border-[#D9D9D3] rounded-2xl p-8 mb-6">
        <div className="flex items-center gap-8">
          <div className="relative w-24 h-24 flex-shrink-0">
            <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
              <circle cx="50" cy="50" r="42" fill="none" stroke="#EBEBE5" strokeWidth="8" />
              <motion.circle
                cx="50" cy="50" r="42" fill="none" stroke={scoreColor} strokeWidth="8"
                strokeLinecap="round" strokeDasharray={2 * Math.PI * 42}
                initial={{ strokeDashoffset: 2 * Math.PI * 42 }}
                animate={{ strokeDashoffset: (2 * Math.PI * 42) * (1 - overallScore / 100) }}
                transition={{ duration: 1.5, ease: [0.16, 1, 0.3, 1] }}
              />
            </svg>
            <div className="absolute inset-0 flex items-center justify-center">
              <span className="font-heading font-bold text-2xl" style={{ color: scoreColor }}>{overallScore}</span>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4 flex-1">
            {[
              { label: 'Files', value: codebase.totalFiles },
              { label: 'Endpoints', value: codebase.endpoints },
              { label: 'Security Issues', value: security.findings, sub: `${security.critical || 0} critical` },
              { label: 'Test Coverage', value: `${unit.coverage || 0}%` },
              { label: 'A11y Score', value: `${accessibility.score || 0}/100` },
              { label: 'Max Users', value: load.maxUsers || 'N/A' },
            ].map((stat) => (
              <div key={stat.label}>
                <div className="text-2xl font-bold text-[#1A1A1A]">{stat.value}</div>
                <div className="text-xs text-[#6B6B6B]">{stat.label}</div>
                {stat.sub && <div className="text-[11px] text-[#D4524A]">{stat.sub}</div>}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Security Findings */}
      {security.items && security.items.length > 0 && (
        <div className="bg-white border border-[#D9D9D3] rounded-2xl p-6 mb-4">
          <div className="flex items-center gap-2 mb-4">
            <Shield size={18} className="text-[#5A8F5E]" />
            <h3 className="font-semibold text-[#1A1A1A]">Security Findings ({security.items.length})</h3>
          </div>
          <div className="space-y-2 max-h-[400px] overflow-y-auto">
            {security.items.slice(0, 15).map((finding: any, i: number) => (
              <div key={i} className="border border-[#D9D9D3] rounded-lg overflow-hidden">
                <button
                  onClick={() => setExpandedFinding(expandedFinding === i ? null : i)}
                  className="w-full flex items-start gap-3 px-4 py-3 text-left hover:bg-[#F5F5F0] transition-colors"
                >
                  <SeverityBadge severity={finding.severity} />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-[#333333]">{finding.title}</p>
                    <p className="text-xs text-[#9A9A9A] font-mono mt-0.5">
                      {finding.filePath}{finding.lineNumber ? `:${finding.lineNumber}` : ''}
                    </p>
                  </div>
                </button>
                {expandedFinding === i && finding.fixSuggestion && (
                  <div className="px-4 pb-3 border-t border-[#D9D9D3] bg-[#F5F5F0] pt-3">
                    <p className="text-xs text-[#6B6B6B] font-mono uppercase mb-1">Fix</p>
                    <p className="text-sm text-[#333333]">{finding.fixSuggestion}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tech Stack */}
      <div className="bg-white border border-[#D9D9D3] rounded-2xl p-6 mb-4">
        <h3 className="font-semibold text-[#1A1A1A] mb-3">Detected Tech Stack</h3>
        <div className="flex flex-wrap gap-2">
          {(codebase.techStack || ['Node.js']).map((tech: string) => (
            <span key={tech} className="px-3 py-1.5 bg-[#E8F0E8] border border-[#A3C9A5] rounded-md font-mono text-xs text-[#5A8F5E]">
              {tech}
            </span>
          ))}
        </div>
      </div>

      {/* Export + Restart */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex gap-2">
          {[
            { format: 'json', label: 'Export JSON', icon: FileJson },
            { format: 'markdown', label: 'Export Markdown', icon: FileText },
            { format: 'pdf', label: 'Export PDF', icon: FileDown },
          ].map((btn) => (
            <button
              key={btn.format}
              onClick={() => handleExport(btn.format)}
              disabled={btn.format === 'pdf'}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg border text-sm font-medium transition-all ${
                btn.format === 'pdf'
                  ? 'border-[#D9D9D3] text-[#9A9A9A] cursor-not-allowed'
                  : 'border-[#D9D9D3] text-[#333333] hover:bg-[#F5F5F0] hover:border-[#A3C9A5]'
              }`}
            >
              <btn.icon size={16} />
              {exportFormat === btn.format ? 'Exported!' : btn.label}
            </button>
          ))}
        </div>
        <button
          onClick={onRestart}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-[#6B6B6B] hover:text-[#1A1A1A] transition-colors"
        >
          <RotateCcw size={16} />
          Test Another Repo
        </button>
      </div>
    </motion.div>
  );
}
